#include "widget_window.h"
#include <QApplication>
#include <QCloseEvent>
#include <QContextMenuEvent>
#include <QGuiApplication>
#include <QHBoxLayout>
#include <QKeyEvent>
#include <QLabel>
#include <QLocale>
#include <QMenu>
#include <QMouseEvent>
#include <QScreen>
#include <QScrollArea>
#include <QSlider>
#include <QSet>
#include <QStyle>
#include <QVBoxLayout>
#include <QWidgetAction>

namespace { constexpr auto Accent = "#61DBB4"; constexpr auto Text = "#E5E2E1"; constexpr auto Muted = "#ADABAA"; }
class ModelRowWidget final : public QWidget {
public:
    ModelRowWidget(const ModelBreakdown &model, QWidget *parent) : QWidget(parent) { auto *layout = new QHBoxLayout(this); layout->setContentsMargins(0, 12, 0, 0); layout->setSpacing(16); name = new QLabel(ModelDisplayNameRules::format(model.model), this); cost = new QLabel(this); name->setStyleSheet(QString("color:%1;").arg(Text)); cost->setStyleSheet(QString("color:%1;").arg(Muted)); layout->addWidget(name, 1); layout->addWidget(cost); setCost(model.cost, false); }
    void setCost(double value, bool highlight) { cost->setText(QLocale(QLocale::English, QLocale::UnitedStates).toCurrencyString(value, "$", 3)); cost->setStyleSheet(QString("color:%1;").arg(highlight ? Accent : Muted)); }
    void clearHighlight() { cost->setStyleSheet(QString("color:%1;").arg(Muted)); }
private: QLabel *name; QLabel *cost;
};
WidgetWindow::WidgetWindow(Settings &settings, SettingsStore &store, UsagePoller &poller) : m_settings(settings), m_store(store), m_poller(poller) {
    setWindowFlags(Qt::FramelessWindowHint | Qt::Tool | (settings.alwaysOnTop ? Qt::WindowStaysOnTopHint : Qt::WindowFlags())); setAttribute(Qt::WA_TranslucentBackground); setWindowOpacity(qBound(0.05, settings.opacity, 1.0)); setFocusPolicy(Qt::StrongFocus);
    auto *card = new QWidget(this); card->setObjectName("card"); m_cardLayout = new QVBoxLayout(card); m_cardLayout->setContentsMargins(settings.isExpanded ? 18 : 12, settings.isExpanded ? 12 : 8, settings.isExpanded ? 18 : 12, settings.isExpanded ? 12 : 8); m_cardLayout->setSpacing(0); m_total = new QLabel("$0.00", card); m_total->setAlignment(Qt::AlignCenter); m_total->setObjectName("total"); m_empty = new QLabel("no usage yet", card); m_empty->setAlignment(Qt::AlignCenter); m_empty->setStyleSheet(QString("color:%1;").arg(Muted)); m_empty->hide(); m_error = new QLabel(card); m_error->setWordWrap(true); m_error->setStyleSheet("color:#E0B341;"); m_error->hide(); m_rowsHost = new QWidget(card); m_rowsLayout = new QVBoxLayout(m_rowsHost); m_rowsLayout->setContentsMargins(0, 0, 0, 0); m_rowsLayout->setSpacing(0); m_scroll = new QScrollArea(card); m_scroll->setWidget(m_rowsHost); m_scroll->setWidgetResizable(false); m_scroll->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff); m_scroll->setMaximumHeight(320); m_scroll->setFrameShape(QFrame::NoFrame); m_scroll->hide(); m_cardLayout->addWidget(m_total); m_cardLayout->addWidget(m_empty); m_cardLayout->addWidget(m_scroll); m_cardLayout->addWidget(m_error);
    auto *root = new QVBoxLayout(this); root->setContentsMargins(0, 0, 0, 0); root->setSizeConstraint(QLayout::SetFixedSize); root->addWidget(card); setStyleSheet("#card { background:#20201F; border:1px solid #4A4A4A; border-radius:4px; } QLabel { font-family:'Cascadia Mono'; font-size:14px; } QMenu, QSlider { font-family:Inter; } #total { font-size:24px; font-weight:bold; color:#E5E2E1; } QMenu { background:#20201F; color:#E5E2E1; border:1px solid #4A4A4A; } QMenu::item:selected { background:#2A2A2A; }");
    m_highlightTimer.setSingleShot(true); connect(&m_highlightTimer, &QTimer::timeout, this, [this] { m_total->setStyleSheet("color:#E5E2E1;"); for (auto *row : m_rows) row->clearHighlight(); }); m_saveTimer.setSingleShot(true); m_saveTimer.setInterval(500); connect(&m_saveTimer, &QTimer::timeout, this, [this] { m_store.save(m_settings); }); connect(&m_poller, &UsagePoller::updated, this, &WidgetWindow::applySnapshot); connect(&m_poller, &UsagePoller::failed, this, &WidgetWindow::showError);
    if (!qIsNaN(settings.x) && !qIsNaN(settings.y)) move(qRound(settings.x), qRound(settings.y)); else { const QRect r = screen()->availableGeometry(); move(r.center() - rect().center()); }
    m_scroll->setVisible(settings.isExpanded);
}
void WidgetWindow::applySnapshot(const DayUsageSnapshot &snapshot) { m_error->hide(); m_total->show(); const QString total = QLocale(QLocale::English, QLocale::UnitedStates).toCurrencyString(snapshot.cost, "$", 2); const bool changed = !m_firstUpdate && total != m_total->text(); m_total->setText(total); m_total->setStyleSheet(changed ? QString("color:%1;").arg(Accent) : QString("color:%1;").arg(Text)); updateRows(snapshot.models); if (changed) m_highlightTimer.start(2000); if (m_firstUpdate) { m_firstUpdate = false; show(); clampToScreen(); } }
void WidgetWindow::showError(const QString &error) { m_total->hide(); m_scroll->hide(); m_empty->hide(); m_error->setText(error); m_error->show(); if (m_firstUpdate) { m_firstUpdate = false; show(); clampToScreen(); } }
QString WidgetWindow::modelKey(const ModelBreakdown &m) const { return m.provider.isEmpty() ? m.model : m.provider + '/' + m.model; }
void WidgetWindow::updateRows(const QList<ModelBreakdown> &models) { QSet<QString> wanted; bool anyHighlight = false; for (const auto &model : models) { const QString key = modelKey(model); const QString value = QLocale(QLocale::English, QLocale::UnitedStates).toCurrencyString(model.cost, "$", 3); const bool highlight = m_previousCosts.contains(key) && m_previousCosts.value(key) != value; m_previousCosts.insert(key, value); if (model.cost < 0.0005) continue; wanted.insert(key); auto *row = m_rows.value(key); if (!row) { row = new ModelRowWidget(model, m_rowsHost); m_rows.insert(key, row); m_rowsLayout->addWidget(row); } row->setCost(model.cost, highlight); anyHighlight |= highlight; }
    for (auto it = m_rows.begin(); it != m_rows.end();) { if (!wanted.contains(it.key())) { delete it.value(); it = m_rows.erase(it); } else ++it; } m_rowsLayout->activate(); const QSize contentSize = m_rowsLayout->sizeHint(); const bool needsScrollBar = contentSize.height() > m_scroll->maximumHeight(); const int scrollBarWidth = needsScrollBar ? style()->pixelMetric(QStyle::PM_ScrollBarExtent) : 0; m_rowsHost->setFixedSize(contentSize); m_scroll->setFixedSize(contentSize.width() + scrollBarWidth, qMin(contentSize.height(), m_scroll->maximumHeight())); m_empty->setVisible(m_settings.isExpanded && m_rows.isEmpty()); m_scroll->setVisible(m_settings.isExpanded && !m_rows.isEmpty()); if (anyHighlight) m_highlightTimer.start(2000); }
void WidgetWindow::toggleExpanded() { m_settings.isExpanded = !m_settings.isExpanded; const int horizontal = m_settings.isExpanded ? 18 : 12; const int vertical = m_settings.isExpanded ? 12 : 8; m_cardLayout->setContentsMargins(horizontal, vertical, horizontal, vertical); m_scroll->setVisible(m_settings.isExpanded && !m_rows.isEmpty()); m_empty->setVisible(m_settings.isExpanded && m_rows.isEmpty()); adjustSize(); saveSoon(); }
void WidgetWindow::saveSoon() { m_settings.x = x(); m_settings.y = y(); m_saveTimer.start(); }
void WidgetWindow::clampToScreen() { QScreen *s = QGuiApplication::screenAt(frameGeometry().center()); if (!s) s = screen(); const QRect r = s->availableGeometry(); move(qBound(r.left(), x(), qMax(r.left(), r.right() - width() + 1)), qBound(r.top(), y(), qMax(r.top(), r.bottom() - height() + 1))); }
void WidgetWindow::center(bool horizontal) { QScreen *target = QGuiApplication::screenAt(frameGeometry().center()); if (!target) target = screen(); const QRect r = target->availableGeometry(); if (horizontal) move(r.x() + (r.width() - width()) / 2, y()); else move(x(), r.y() + (r.height() - height()) / 2); saveSoon(); }
void WidgetWindow::mousePressEvent(QMouseEvent *event) { if (event->button() == Qt::LeftButton) { m_dragStart = event->globalPosition().toPoint(); m_dragging = false; } QWidget::mousePressEvent(event); }
void WidgetWindow::mouseMoveEvent(QMouseEvent *event) { if (event->buttons() & Qt::LeftButton && (event->globalPosition().toPoint() - m_dragStart).manhattanLength() >= QApplication::startDragDistance()) { move(pos() + event->globalPosition().toPoint() - m_dragStart); m_dragStart = event->globalPosition().toPoint(); m_dragging = true; m_anchorPending = false; } }
void WidgetWindow::mouseReleaseEvent(QMouseEvent *event) { if (event->button() == Qt::LeftButton) { if (!m_dragging) toggleExpanded(); else { clampToScreen(); saveSoon(); } } }
void WidgetWindow::contextMenuEvent(QContextMenuEvent *event) { buildMenu(event->globalPos()); }
void WidgetWindow::buildMenu(const QPoint &at) { auto *menu = new QMenu(this); auto *top = menu->addAction("Always on top"); top->setCheckable(true); top->setChecked(m_settings.alwaysOnTop); connect(top, &QAction::triggered, this, [this](bool on) { m_settings.alwaysOnTop = on; setWindowFlag(Qt::WindowStaysOnTopHint, on); show(); saveSoon(); }); menu->addSeparator(); auto addSlider = [this, menu](const QString &title, int min, int max, int value, auto changed) { auto *action = new QWidgetAction(menu); auto *host = new QWidget(menu); auto *l = new QHBoxLayout(host); auto *label = new QLabel(title, host); auto *slider = new QSlider(Qt::Horizontal, host); slider->setRange(min, max); slider->setSingleStep(5); slider->setValue(value); l->addWidget(label); l->addWidget(slider); connect(slider, &QSlider::valueChanged, this, changed); action->setDefaultWidget(host); menu->addAction(action); }; addSlider("Poll interval", 5, 60, qRound(m_settings.pollIntervalSeconds), [this](int v) { m_settings.pollIntervalSeconds = v; m_poller.setInterval(v); saveSoon(); }); addSlider("Opacity", 5, 100, qRound(m_settings.opacity * 100), [this](int v) { m_settings.opacity = v / 100.0; setWindowOpacity(m_settings.opacity); saveSoon(); }); menu->addAction("Center horizontally", [this] { center(true); }); menu->addAction("Center vertically", [this] { center(false); }); menu->addAction("Hide", this, &QWidget::hide); menu->addAction("Exit", [this] { m_exitRequested = true; qApp->quit(); }); menu->exec(at); menu->deleteLater(); }
void WidgetWindow::closeEvent(QCloseEvent *event) { if (!m_exitRequested) { event->ignore(); hide(); } else { m_settings.x = x(); m_settings.y = y(); m_store.save(m_settings); event->accept(); } }
void WidgetWindow::resizeEvent(QResizeEvent *event) { if (event->oldSize().isEmpty()) return; const QSize delta = event->size() - event->oldSize(); QScreen *s = QGuiApplication::screenAt(frameGeometry().center()); if (!s) return; const QPoint c = s->availableGeometry().center(); if (!m_anchorPending) { m_anchorRight = frameGeometry().center().x() > c.x(); m_anchorBottom = frameGeometry().center().y() > c.y(); m_anchorPending = true; } else { m_anchorPending = false; } move(x() - (m_anchorRight ? delta.width() : 0), y() - (m_anchorBottom ? delta.height() : 0)); }
void WidgetWindow::keyPressEvent(QKeyEvent *event) { if (event->key() == Qt::Key_T) toggleExpanded(); else if (event->key() == Qt::Key_H) center(true); else if (event->key() == Qt::Key_V) center(false); else if (event->key() == Qt::Key_A) { m_settings.alwaysOnTop = !m_settings.alwaysOnTop; setWindowFlag(Qt::WindowStaysOnTopHint, m_settings.alwaysOnTop); show(); saveSoon(); } else QWidget::keyPressEvent(event); }
